### ISSUE TITLE
Backend crash

### ISSUE THREAD

**Issue by akuehnis** [PrestaShop/ps_imageslider#9]
PS 1.7 RC 2, cant configure ps_imageslider
(fresh install)

calling this url: /index.php?controller=AdminModules&configure=ps_imageslider

Error message: 
[PrestaShop] Fatal error in module file :.../app/bootstrap.php.cache:
Uncaught exception 'SmartyException' with message 'Unknown resource type 'module'' in ..../vendor/prestashop/smarty/sysplugins/smarty_resource.php:467 Stack trace: #0 .../vendor/prestashop/smarty/sysplugins/smarty_resource.php(544): Smarty_Resource::load(Object(Smarty), 'module') #1 .../vendor/prestashop/smarty/sysplugins/smarty_internal_template.php(680): Smarty_Resource::source(Object(Smarty_Internal_Template)) #2 .../vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php(119): Smarty_Internal_Template->__get('source') #3 .../classes/module/Module.php(2265): Smarty_Internal_TemplateBase->fetch() #4 .../modules/ps_imageslider/ps_imageslider.php(713): ModuleCore->fetch('module:ps_image...') #5 .../modules/ps_imageslider/ps_imageslider.php(280): Ps_ImageSlider->renderList()

**Comment by ludohenin** [comment]
Yup, this is still true with the v1.0.5 of the module and PS-RC3.
`Unknown resource type 'module'`

**Comment by maximebiloe** [comment]
Thanks for this report.
We just fixed it here: https://github.com/PrestaShop/ps_imageslider/commit/905515cb153ec9cf0e529f6fd0f88fbc95378586

Regards

**Comment by ludohenin** [comment]
Awesome, thanks for the (very) quick fix!
